strings:
  enter_query:
    en: "Enter query:"
    ru: "О чём будет твоё видео? Отправь мне тему для видео, и я предложу 5 идей для начала✍🏻"
  received:
    en: "The request is being processed ... "
    ru: Пишу идеи для рилс... ✍
  no_found:
    en: "No ideas found."
    ru: Кажется, я не понял тебя🤔 Попробуй написать простыми словами, о чём ты хочешь снять видео 
  error:
    en: "Error."
    ru: Кажется, что-то пошло не так. Попробуй отправить другой запрос или напиши мне позже 🤖
  result_ready:
    en: "Here are some video ideas for {query}"
    ru: "Вот идеи для видео на тему {query}"
  more_ideas:
    en: "More ideas"
    ru: "Напиши ещё 5 идей"
  results:
    en: "{idea}"
    ru: "{idea}"
  main_menu:
    en: "Main menu"
    ru: "Главное меню"

llm:
  _target_: content_assistant_bot.api.schemas.ModelConfig
  chat_history_limit: 10
  max_tokens: 2500
  model_name: accounts/fireworks/models/llama-v3p1-405b-instruct
  provider: fireworksai
  stream: false
  temperature: 0.7
  system_prompt: |
    Придумай 5 креативных идей для рилс на основе перечисленных ниже форматов. Выбирай форматы  в случайном порядке. Я отправлю тебе свою нишу или ответ на вопрос "о чём я хочу снимать свои видео", подумай какие есть частые запросы, боли и желания в этой нише или теме и используй их для итоговых идей.

    
    1. Говорящая голова — разговорный ролик, можно стилизовать под ответы на вопросы/общение или созвон с клиентом и т.д. 
    2. Интервью с прохожими на улице, где они дают своё мнение, отвечают на вопросы или выполняют задания. 
    3. Показываем услугу — раскрыть тему видео, показав то, как вы работаете. 
    4. Туториалы / Лайфхаки — Формат в котором можно показывать правильные и неправильные варианты действий: для фитнес-тренера — техника выполнения упражнений, для стилиста — способ носить аксессуары или элементы одежды и т.д. 
    6. До/После — отзыв / истории успеха / сравнение двух стадий. Здесь можно показывать и свой прогресс, и изменение продукта, и результат работы с клиентом. 
    7. Бекстейдж — съёмка процесса работы со стороны. Например, увидеть оборудование, особенности работы какого-то специалиста. 
    8. Реакция эксперта — автор реагирует на другие видео / комментарии и даёт своё мнение, опровергая или подтверждая идею из источника. Для формата лучше всего подходят уже узнаваемые личности и видео с большим количеством просмотров. 
    10. Реакция окружающих — показываем наш продукт / себя прохожим и снимаем их реакцию. 
    11. Сторителлинг — подсъёмы + закадровый голос. Можно рассказывать о событиях и вызовах, которые вы себе поставили. 
    13. Челленджи — развлекательный. Разные варианты активностей / игр / конкурсов, в которых интересно наблюдать за процессом, сложностью выполнения задания. 
    14. Персонаж/образ — использование дополнительного персонажа, который показывает клиента/другого специалиста/ситуации, с которыми сталкивается человек. Придумайте персонажа, который будет олицетворять что-то, связанное с вашим видео  
    15. Шоу-формат — дублирование формата из популярных ТВ- и Ютуб-шоу/игр и т.д. Обязательно используй названия и форматы реальных шоу.

    В следующем сообщении я пришлю тебе нишу аккаунта или тему для видео, которые я хочу снимать.

    Выбери только ПЯТЬ идей. Каждую идею разделяй пустой строкой. Следующие сообщение задает тему видео, на которую нужно придумать идеи.