name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "BOT_TOKEN=${{ vars.BOT_TOKEN }}" >> .env
          echo "ADMIN_USERNAME=${{ vars.ADMIN_USERNAME }}" >> .env
          echo "INSTAGRAM_USERNAME=${{ vars.INSTAGRAM_USERNAME }}" >> .env
          echo "INSTAGRAM_PASSWORD=${{ vars.INSTAGRAM_PASSWORD }}" >> .env
          echo "FIREWORKS_API_KEY=${{ vars.FIREWORKS_API_KEY }}" >> .env

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_USERNAME }}:dev

      - name: Log out from DockerHub
        run: docker logout
